kind: PersistentVolume
apiVersion: v1
metadata:
  name: identity-pv-volume
  labels:
    type: local
    app: identity
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: identity-pv-claim
  labels:
    app: identity
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  selector:
    matchLabels:
      app: identity
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: identity
        tier: frontend
        track: stable
    spec:
      initContainers:
        - name: create-db
          image: jbergknoff/postgresql-client
          command: ["psql", "-d", "$(DATASOURCE)", "-f", "/sql/create-db.sql"]
          env:
            - name: DATASOURCE
              valueFrom:
                  configMapKeyRef:
                    name: postgres-config-admin
                    key: DATASOURCE
          volumeMounts:
          - name: sql
            mountPath: /sql
      containers:
        - name: identity
          image: ${IMAGE}
          imagePullPolicy: Always
          volumeMounts:
            - name: certs
              mountPath: /srv/certs
            - name: config
              mountPath: /srv/config
          env:
            - name: PORT
              value: "8030"
            - name: DRIVER
              value: "postgres"
            - name: DATASOURCE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-identity
                  key: DATASOURCE
            - name: MQTTURL
              value: "${MQTTURL}"
            - name: MQTTPORT
              value: "8883"
            - name: CERTSDIR
              value: "/srv/certs"
            - name: LOG_FORMAT
              value: "json"
          ports:
            - containerPort: 8030
      volumes:
        - name: certs
          secret:
            secretName: identity-certs
        - name: config
          persistentVolumeClaim:
            claimName: identity-pv-claim
        - name: sql
          configMap:
            name: postgres-config-identity
            items:
            - key: DB_CREATE_SQL
              path: create-db.sql
---
apiVersion: v1
kind: Service
metadata:
  name: identity
spec:
  selector:
    app: identity
    tier: frontend
  ports:
    - port: 8030
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: identity-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${CERT_ARN}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: identity
    tier: frontend
  ports:
    - name: https
      port: 443
      targetPort: 8030
      protocol: TCP
  type: LoadBalancer
  loadBalancerSourceRanges:
    %{ for ip in IP_WHITELIST ~}
    - ${ip}
    %{ endfor ~}